kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Chart.Name }}-pv-claim  # Sets name of PVC
  labels:
    app: {{ .Chart.Name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany  # Sets read and write access
  resources:
    requests:
      storage: {{ .Values.storage.pvSize }}  # Sets volume size