apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ui.externalPort }}
      targetPort: {{ .Values.service.ui.internalPort }}
      protocol: TCP
      name: {{ .Values.service.ui.name }}
    - port: {{ .Values.service.tcp.externalPort }}
      targetPort: {{ .Values.service.tcp.internalPort }}
      protocol: TCP
      name: {{ .Values.service.tcp.name }}      
    - port: {{ .Values.service.quic.externalPort }}
      targetPort: {{ .Values.service.quic.internalPort }}
      protocol: UDP
      name: {{ .Values.service.quic.name }}
    - port: {{ .Values.service.local.externalPort }}
      targetPort: {{ .Values.service.local.internalPort }}
      protocol: UDP
      name: {{ .Values.service.local.name }}
  selector:
    app: {{.Release.Name}}-{{ .Chart.Name }}